=== alexmvarela/fpdaw-xml/dtd-validation/centro.dtd
<!-- centro.dtd -->
<!ELEMENT centro (ciclo+)>
<!ATTLIST centro
          xmlns:módulos CDATA #IMPLIED
          xmlns:alumnos CDATA #IMPLIED>

<!ELEMENT ciclo (módulos, alumnos)>
<!ATTLIST ciclo id CDATA #REQUIRED
                grao CDATA #REQUIRED>

<!ELEMENT módulos (módulos:módulo+)>
<!ELEMENT módulos:módulo (módulos:nome, módulos:horas)>
<!ATTLIST módulos:módulo id CDATA #REQUIRED>
<!ELEMENT módulos:nome (#PCDATA)>
<!ELEMENT módulos:horas (#PCDATA)>

<!ELEMENT alumnos (alumnos:alumno+)>
<!ELEMENT alumnos:alumno (alumnos:nome, alumnos:apelidos, alumnos:datanacemento, alumnos:nota, alumnos:módulo+)>
<!ELEMENT alumnos:nome (#PCDATA)>
<!ELEMENT alumnos:apelidos (#PCDATA)>
<!ELEMENT alumnos:datanacemento (#PCDATA)>
<!ELEMENT alumnos:nota (#PCDATA)>
<!ELEMENT alumnos:módulo EMPTY>
<!ATTLIST alumnos:módulo id CDATA #REQUIRED
                         nota CDATA #REQUIRED>

=== alexmvarela/fpdaw-xml/dtd-validation/centro.xml
<?xml version="1.1" encoding="utf-8"?>
<!-- centro.xml -->
<!DOCTYPE centro SYSTEM "centro.dtd">
<centro xmlns:módulos="http://www.iesrodeira.com/modulos" xmlns:alumnos="http://www.iesrodeira.com/alumnos">
  <ciclo id="ASIR" grao="CS">

    <módulos>
      <módulos:módulo id="MP0370">
        <módulos:nome>Planificación e administración de redes</módulos:nome>
        <módulos:horas>213</módulos:horas>
      </módulos:módulo>

      <módulos:módulo id="MP0371">
        <módulos:nome>Fundamentos hardware</módulos:nome>
        <módulos:horas>107</módulos:horas>
      </módulos:módulo>
    </módulos>

    <alumnos>
      <alumnos:alumno>
        <alumnos:nome>Xoan</alumnos:nome>
        <alumnos:apelidos>Cancedo da Foz</alumnos:apelidos>
        <alumnos:datanacemento>06/11/1991</alumnos:datanacemento>
        <alumnos:nota>Xa fixo outro ciclo</alumnos:nota>
        <alumnos:módulo id="MP0370" nota="7"/>
        <alumnos:módulo id="MP0371" nota="8"/>
      </alumnos:alumno>
      
      <alumnos:alumno>
        <alumnos:nome>Alicia</alumnos:nome>
        <alumnos:apelidos>Fernández Pérez</alumnos:apelidos>
        <alumnos:datanacemento>12/08/1992</alumnos:datanacemento>
        <alumnos:nota>Fixo ben o ciclo</alumnos:nota>
        <alumnos:módulo id="MP0370" nota="6"/>
        <alumnos:módulo id="MP0371" nota="7"/>
      </alumnos:alumno>
    </alumnos>

  </ciclo>
</centro>
