=== alexmvarela/fpdaw-xml/dtd-validation/personas.dtd
<!ELEMENT personas (persona+)>

<!ELEMENT persona (nombre, nacimiento?, direccion+, varon)>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT nacimiento EMPTY>
<!ELEMENT direccion (calle, poblacion, provincia, cpostal)>
<!ELEMENT varon EMPTY>

<!ELEMENT calle (#PCDATA)>
<!ELEMENT poblacion (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT cpostal (#PCDATA)>

<!ATTLIST nacimiento
    dia CDATA #REQUIRED
    mes CDATA #REQUIRED
    anyo CDATA #REQUIRED>

=== alexmvarela/fpdaw-xml/dtd-validation/personas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE personas SYSTEM "personas.dtd">
<personas>
  <persona>
    <nombre>Juan Pardo</nombre>
    <nacimiento dia="10" mes="Abril" anyo="1982"/>
    <direccion>
      <calle>Caoba, 1</calle>
      <poblacion>Madrid</poblacion>
      <provincia>Madrid</provincia>
      <cpostal>28005</cpostal>
    </direccion>
    <varon/>
  </persona>
  <persona>
    <nombre>Javier López</nombre>
    <direccion>
      <calle>Gran Vía, 10</calle>
      <poblacion>Vigo</poblacion>
      <provincia>Pontevedra</provincia>
      <cpostal>36211</cpostal>
    </direccion>
    <varon/>
  </persona>
</personas>
